DROP TABLE IF EXISTS nxcore_staging_mmquotes;
CREATE EXTERNAL TABLE nxcore_staging_mmquotes (
		system_date				string,
		system_time				string,
		system_timezone			string,
		system_dst_indicator	string,
		system_ndays			string,
		system_dayofweek		string,
		system_dayofyear		string,
		nxsession_date			string,
		nxsession_dst_indicator	string,
		nxsession_ndays			string,
		nxsession_dayofweek		string,
		nxsession_dayofyear		string,
		nxexg_time				string,
		nxexg_timezone			string,
		symbol					string,
		listed_exg				string,
		reporting_exg			string,
		session_id				string,
		exg_ask_price			string,
		--exg_ask_price_change_int	string,
		exg_ask_price_change	string,
		exg_ask_size				string,
		exg_ask_size_change		string,
		--exg_bid_price_int		string,
		exg_bid_price_double		string,
		--exg_bid_price_change_int	string,
		exg_bid_price_change	string,
		exg_bid_size				string,
		exg_bid_size_change		string,
		exg_nasdaq_bid_tick		string,
		exg_price_type			string,
		exg_quote_condition_id	string,
		--exg_quote_condition_string string,
		exg_refresh				string,
		exg_bbo_change_flags	string,
		exg_best_ask_condition	string,
		exg_best_ask_exchange	string,
		exg_best_ask_price		string,
		exg_best_ask_price_change	string,
		exg_best_ask_size		string,
		exg_best_ask_size_change	string,
		exg_best_bid_condition	string,
		exg_best_bid_exchange	string,
		exg_best_bid_price		string,
		exg_best_bid_price_change	string,
		exg_best_bid_size		string,
		exg_best_bid_size_change	string,
		exg_closing_quote_flag	string,
		exg_prev_best_ask_exchange	string,
		exg_prev_best_bid_exchange string
		) ROW FORMAT DELIMITED 
			FIELDS TERMINATED BY '\t'
			LINES TERMINATED BY '\n'
		STORED AS TEXTFILE
		LOCATION '/data/staging/nxcore/exgquotes';
