DROP TABLE IF EXISTS nxcore_staging_trades;
CREATE EXTERNAL TABLE nxcore_staging_trades (
		system_date				string,
		system_time				string,
		system_timezone			int,
		system_dst_indicator	int,
		system_ndays			int,
		system_dayofweek		int,
		system_dayofyear		int,
		nxsession_date			string,
		nxsession_dst_indicator	int,
		nxsession_ndays			int,
		nxsession_dayofweek		int,
		nxsession_dayofyear		int,
		nxexg_time				string,
		nxexg_timezone			int,
		symbol					string,
		listed_exg				int,
		reporting_exg			int,
		session_id				int,
		price_flags				int,
		condition_flags			int,
		trade_condition			int,
		trade_volume_type		int,
		trade_bate_code			string,
		trade_size				int,
		trade_exg_sequence		int,
		trade_records_back		int,
		trade_total_volume		bigint,
		trade_tick_volume		int,
		trade_price				double,
		trade_open				double,
		trade_high				double,
		trade_low				double,
		trade_last				double,
		trade_tick				double,
		trade_netchange			double,
		analysis_filter_thresh	double,
		analysis_filtered		int,
		analysis_filter_level	int,
		analysis_sighilotype	int,
		analysis_sighiloseconds	int,
		analysis_qte_matchdistance_rgn	int,
		analysis_qte_matchdistance_bbo	int,
		analysis_qte_matchflags_bbo	int,
		analysis_qte_matchflags_rgn	int,
		analysis_qte_matchtype_bbo	int,
		analysis_qte_matchtype_rgn	int
		-- null_column	int      -- NO LONGER NECESSARY FIXED IN ProcessTape V2
		) ROW FORMAT DELIMITED 
			FIELDS TERMINATED BY '\t'
			LINES TERMINATED BY '\n'
		STORED AS TEXTFILE
		LOCATION '/data/staging/nxcore/trades';
